version: '3.8'

services:
  bot:
    build:
      context: .
    env_file:
      - .env
    container_name: discord_bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - STEAM_API_KEY=${STEAM_API_KEY}
      - CL_API_KEY=${CL_API_KEY}
      - GIT_COMMIT=${GIT_COMMIT:-unknown}
      - GIT_BRANCH=${GIT_BRANCH:-unknown}
    volumes:
      - ./data:/app/data
      - .:/app
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: discord_bot_network 