version: '3.8'

services:
  bot:
    build: .
    container_name: discord_bot
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_TOKEN}
      - OPENWEATHER_API_KEY=${WEATHER_API_KEY}
      - STEAM_API_KEY=${STEAM_API_KEY}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: discord_bot_network 