version: '3.8'

services:
  bot:
    build:
      context: .
      args:
        - GIT_COMMIT=$(git rev-parse --short HEAD)
        - GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
    env_file:
      - .env
    container_name: discord_bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - STEAM_API_KEY=${STEAM_API_KEY}
    volumes:
      - ./data:/app/data
      - .:/app
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: discord_bot_network 