name: Auto PR to Main

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto PR from develop"
          title: "Auto PR: Develop to Main"
          body: |
            Automated PR from develop to main
            
            Changes included in this PR:
            - Please review the changes below
            
            Note: This PR was automatically created by GitHub Actions
          branch: develop
          base: main
          delete-branch: false 