name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/discord_local
          echo "TOKEN = '${{ secrets.DISCORD_TOKEN }}'" > config.py
          echo "STEAM_KEY = '${{ secrets.STEAM_API_KEY }}'" >> config.py
          echo "WEATHER_API_KEY = '${{ secrets.WEATHER_API_KEY }}'" >> config.py
          git pull
          docker-compose down
          docker-compose build
          docker-compose up -d 